#!/usr/bin/env bash
# Shrink output -> restrained heating -> NPT equilibration -> production.
#
# Usage:
#   ./run_equilibration.sh <shrink_workdir> <system.top> <outdir> [stage]
#     stage: heat | npt | production | all (default all)
#
# The shrink hands over last_valid.gro (or final.gro) and the build's
# system.top. Heavy-atom position restraints are generated here from the
# hydrogel ITP's masses -- no index groups, no guessing by element name --
# into a copy of the topology, so the original topology is never edited.
# POSRES_FC is stepped 1000 -> 200 -> 0 kJ/mol/nm^2 over three heating runs.
#
# Cores follow the allocation (--omp/SLURM_CPUS_PER_TASK/OMP_NUM_THREADS),
# never a survey of the node. GROMACS honours CUDA_VISIBLE_DEVICES itself.
#
# Nothing here declares equilibrium. Run check_convergence.py on the NPT
# energy file; production starts only when it reports a plateau.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
shrink="${1:?shrink workdir}"; top="${2:?system.top}"; out="${3:?outdir}"; stage="${4:-all}"
omp="${OMP_NUM_THREADS:-${SLURM_CPUS_PER_TASK:-}}"
ntomp=(); [[ -n "$omp" ]] && ntomp=(-ntomp "$omp")
gmx="${GMX:-gmx_mpi}"
maxwarn="${MAXWARN:-1}"

start="$shrink/last_valid.gro"; [[ -f "$shrink/final.gro" ]] && start="$shrink/final.gro"
mkdir -p "$out"

# --- topology copy with a POSRES block appended to the hydrogel ITP ---------
# The hydrogel moleculetype is the last section of its ITP, so appending a
# [ position_restraints ] block there keeps it inside that moleculetype.
if [[ ! -f "$out/system_posres.top" ]]; then
  python3 - "$top" "$out" <<'PY'
import os, re, sys
top, out = sys.argv[1], sys.argv[2]
text = open(top).read()
hyd = [m.group(1) for m in re.finditer(r'#include\s+"([^"]+initial_hydrogel\.itp)"', text)]
if len(hyd) != 1:
    sys.exit(f"expected exactly one initial_hydrogel.itp include in {top}, found {hyd}")
src = hyd[0] if os.path.isabs(hyd[0]) else os.path.join(os.path.dirname(top), hyd[0])
lines = open(src).read().split("\n")
sec = None; heavy = []
for l in lines:
    t = l.split(";", 1)[0].strip()
    if not t: continue
    if t.startswith("["): sec = t.strip("[] ").lower(); continue
    if sec == "atoms":
        p = t.split()
        if len(p) >= 8 and float(p[7]) > 1.5: heavy.append(int(p[0]))
posre = os.path.join(out, "posre_heavy.itp")
with open(posre, "w") as f:
    f.write("; heavy-atom position restraints, generated by run_equilibration.sh\n")
    f.write("; POSRES_FC is set by the mdp (define = -DPOSRES_FC=...)\n")
    f.write("[ position_restraints ]\n; atom  funct  fx  fy  fz\n")
    for i in heavy:
        f.write(f"{i:7d}  1  POSRES_FC  POSRES_FC  POSRES_FC\n")
patched = os.path.join(out, "initial_hydrogel_posres.itp")
with open(patched, "w") as f:
    f.write("\n".join(lines).rstrip("\n") + "\n\n#ifdef POSRES\n#include \"posre_heavy.itp\"\n#endif\n")
new_top = text.replace(f'"{hyd[0]}"', f'"{patched}"')
open(os.path.join(out, "system_posres.top"), "w").write(new_top)
print(f"posres: {len(heavy)} heavy atoms restrained; topology copy {out}/system_posres.top")
PY
fi
top_posres="$out/system_posres.top"

run() {  # run <name> <mdp> <start.gro> [extra grompp args...]
  local name="$1" mdp="$2" gro="$3"; shift 3
  local d="$out/$name"; mkdir -p "$d"
  if [[ -f "$d/$name.gro" ]]; then echo "[$name] done already"; return 0; fi
  ( cd "$d" && "$gmx" grompp -f "$mdp" -c "$gro" -r "$gro" -p "$top_posres" -o "$name.tpr" \
        -maxwarn "$maxwarn" "$@" > grompp.log 2>&1 ) || { echo "[$name] grompp failed, see $d/grompp.log"; return 1; }
  ( cd "$d" && "$gmx" mdrun -deffnm "$name" "${ntomp[@]}" > mdrun.log 2>&1 ) \
        || { echo "[$name] mdrun failed, see $d/mdrun.log"; return 1; }
  echo "[$name] ok"
}

# Stage-specific mdps are derived from heat_posres.mdp by swapping POSRES_FC.
stage_mdp() { sed "s/-DPOSRES_FC=1000/-DPOSRES_FC=$1/" "$HERE/heat_posres.mdp" > "$out/heat_fc$1.mdp"; echo "$out/heat_fc$1.mdp"; }

if [[ "$stage" == "heat" || "$stage" == "all" ]]; then
  run heat_fc1000 "$(stage_mdp 1000)" "$start" || exit 1
  run heat_fc200  "$(stage_mdp 200)"  "$out/heat_fc1000/heat_fc1000.gro" || exit 1
  # fc 0: drop the define entirely so no restraint file is even read.
  sed -e '/^define/d' -e 's/^comm-mode .*/comm-mode               = Linear\nnstcomm                 = 100/' \
      "$HERE/heat_posres.mdp" > "$out/heat_free.mdp"
  run heat_free "$out/heat_free.mdp" "$out/heat_fc200/heat_fc200.gro" || exit 1
fi
if [[ "$stage" == "npt" || "$stage" == "all" ]]; then
  run npt_equil "$HERE/npt_equil.mdp" "$out/heat_free/heat_free.gro" -t "$out/heat_free/heat_free.cpt" || exit 1
  echo "now: python3 $HERE/check_convergence.py $out/npt_equil/npt_equil.edr"
fi
if [[ "$stage" == "production" ]]; then
  run production "$HERE/production.mdp" "$out/npt_equil/npt_equil.gro" -t "$out/npt_equil/npt_equil.cpt" || exit 1
fi
