#!/usr/bin/env bash
# Shrink output -> restrained heating -> NPT equilibration -> production.
#
# Usage:
#   ./run_equilibration.sh <shrink_workdir> <system.top> <outdir> [stage]
#     stage: heat | npt | extend | production | all (default all)
#
# "extend" continues the existing npt_equil by EXTEND_NS nanoseconds (default
# 10) from its checkpoint, appending to the same edr/log/xtc so the plateau
# screen sees one continuous record instead of two short ones. Use it when
# check_convergence.py says NOT YET because a term is still drifting.
#
# The shrink hands over last_valid.gro (or final.gro) and the build's
# system.top. Heavy-atom position restraints are generated here from the
# hydrogel ITP's masses -- no index groups, no guessing by element name --
# into a copy of the topology, so the original topology is never edited.
# POSRES_FC is stepped 1000 -> 200 -> 0 kJ/mol/nm^2 over three heating runs.
#
# Cores follow the allocation (--omp/SLURM_CPUS_PER_TASK/OMP_NUM_THREADS),
# never a survey of the node. GROMACS honours CUDA_VISIBLE_DEVICES itself.
#
# Nothing here declares equilibrium. "all" runs heat and NPT only. The
# explicit "production" stage requires a PLATEAU artifact from
# check_convergence.py whose sha256 matches the current NPT energy file --
# and even then that artifact only screens thermodynamic plateaus; structural
# equilibrium is assessed separately.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
shrink="${1:?shrink workdir}"; top="${2:?system.top}"; out="${3:?outdir}"; stage="${4:-all}"
# Same precedence as sizing/run_size.sh: explicit OMP, then the scheduler's
# allocation, then OMP_NUM_THREADS, else GROMACS decides.
omp="${OMP:-${SLURM_CPUS_PER_TASK:-${OMP_NUM_THREADS:-}}}"
ntomp=(); [[ -n "$omp" ]] && ntomp=(-ntomp "$omp")
gmx="${GMX:-gmx_mpi}"
# No blanket warning allowance: a v1 topology preprocesses warning-free, and
# any warning that does appear should be looked at, not waved through.
maxwarn="${MAXWARN:-0}"

start="$shrink/last_valid.gro"; [[ -f "$shrink/final.gro" ]] && start="$shrink/final.gro"
mkdir -p "$out"

# --- topology copy with a POSRES block appended to the hydrogel ITP ---------
# The hydrogel moleculetype is the last section of its ITP, so appending a
# [ position_restraints ] block there keeps it inside that moleculetype.
if [[ ! -f "$out/system_posres.top" ]]; then
  python3 - "$top" "$out" <<'PY'
import os, re, sys
top, out = sys.argv[1], sys.argv[2]
text = open(top).read()
hyd = [m.group(1) for m in re.finditer(r'#include\s+"([^"]+initial_hydrogel\.itp)"', text)]
if len(hyd) != 1:
    sys.exit(f"expected exactly one initial_hydrogel.itp include in {top}, found {hyd}")
src = hyd[0] if os.path.isabs(hyd[0]) else os.path.join(os.path.dirname(top), hyd[0])
lines = open(src).read().split("\n")
sec = None; heavy = []
for l in lines:
    t = l.split(";", 1)[0].strip()
    if not t: continue
    if t.startswith("["): sec = t.strip("[] ").lower(); continue
    if sec == "atoms":
        p = t.split()
        if len(p) >= 8 and float(p[7]) > 1.5: heavy.append(int(p[0]))
posre = os.path.join(out, "posre_heavy.itp")
with open(posre, "w") as f:
    f.write("; heavy-atom position restraints, generated by run_equilibration.sh\n")
    f.write("; POSRES_FC is set by the mdp (define = -DPOSRES_FC=...)\n")
    f.write("[ position_restraints ]\n; atom  funct  fx  fy  fz\n")
    for i in heavy:
        f.write(f"{i:7d}  1  POSRES_FC  POSRES_FC  POSRES_FC\n")
patched = os.path.join(out, "initial_hydrogel_posres.itp")
with open(patched, "w") as f:
    f.write("\n".join(lines).rstrip("\n") + "\n\n#ifdef POSRES\n#include \"posre_heavy.itp\"\n#endif\n")
new_top = text.replace(f'"{hyd[0]}"', f'"{patched}"')
open(os.path.join(out, "system_posres.top"), "w").write(new_top)
print(f"posres: {len(heavy)} heavy atoms restrained; topology copy {out}/system_posres.top")
PY
fi
top_posres="$out/system_posres.top"

run() {  # run <name> <mdp> <start.gro> [extra grompp args...]
  local name="$1" mdp="$2" gro="$3"; shift 3
  local d="$out/$name"; mkdir -p "$d"
  if [[ -f "$d/$name.gro" ]]; then echo "[$name] done already"; return 0; fi
  ( cd "$d" && "$gmx" grompp -f "$mdp" -c "$gro" -r "$gro" -p "$top_posres" -o "$name.tpr" \
        -pp "$name.processed.top" -po "$name.mdout.mdp" -maxwarn "$maxwarn" "$@" > grompp.log 2>&1 ) \
        || { echo "[$name] grompp failed, see $d/grompp.log"; return 1; }
  # Stage manifest: include-resolved topology, tpr, the mdp actually used
  # (with the seed grompp drew when gen_seed = -1) and the input coordinates.
  python3 - "$d" "$name" "$mdp" "$gro" >> "$out/stage_manifest.tsv" <<'PY'
import hashlib, re, sys, os, datetime
d, name, mdp, gro = sys.argv[1:5]
def h(p):
    return hashlib.sha256(open(p, "rb").read()).hexdigest()[:16]
mdout = os.path.join(d, f"{name}.mdout.mdp")
seed = "?"
for line in open(mdout):
    if re.match(r"\s*gen[-_]seed\s*=", line):
        seed = line.split("=", 1)[1].strip()
print("\t".join([datetime.datetime.now().isoformat(timespec="seconds"), name,
                 f"mdp={h(mdp)}", f"gro={h(gro)}", f"tpr={h(os.path.join(d, name + '.tpr'))}",
                 f"processed_top={h(os.path.join(d, name + '.processed.top'))}", f"gen_seed={seed}"]))
PY
  ( cd "$d" && "$gmx" mdrun -deffnm "$name" "${ntomp[@]}" > mdrun.log 2>&1 ) \
        || { echo "[$name] mdrun failed, see $d/mdrun.log"; return 1; }
  echo "[$name] ok"
}

# Stage-specific mdps are derived from heat_posres.mdp. Only the first stage
# generates velocities; the later ones continue from the previous checkpoint,
# so the three stages are one heating with stepwise restraint release, not
# three cold restarts.
stage_mdp() {  # stage_mdp <fc> <continue: 0|1>
  local fc="$1" cont="$2" f="$out/heat_fc$1.mdp"
  sed "s/-DPOSRES_FC=1000/-DPOSRES_FC=$fc/" "$HERE/heat_posres.mdp" > "$f"
  if [[ "$cont" == "1" ]]; then
    sed -i -e 's/^continuation .*/continuation            = yes/' -e 's/^gen_vel .*/gen_vel                 = no/' "$f"
  fi
  echo "$f"
}

if [[ "$stage" == "heat" || "$stage" == "all" ]]; then
  run heat_fc1000 "$(stage_mdp 1000 0)" "$start" || exit 1
  run heat_fc200  "$(stage_mdp 200 1)"  "$out/heat_fc1000/heat_fc1000.gro" -t "$out/heat_fc1000/heat_fc1000.cpt" || exit 1
  # fc 0: drop the define entirely so no restraint file is even read, and
  # restore COM-motion removal now that nothing pins the frame.
  sed -e '/^define/d' -e 's/^comm-mode .*/comm-mode               = Linear\nnstcomm                 = 100/' \
      -e 's/^continuation .*/continuation            = yes/' -e 's/^gen_vel .*/gen_vel                 = no/' \
      "$HERE/heat_posres.mdp" > "$out/heat_free.mdp"
  run heat_free "$out/heat_free.mdp" "$out/heat_fc200/heat_fc200.gro" -t "$out/heat_fc200/heat_fc200.cpt" || exit 1
fi
if [[ "$stage" == "npt" || "$stage" == "all" ]]; then
  run npt_equil "$HERE/npt_equil.mdp" "$out/heat_free/heat_free.gro" -t "$out/heat_free/heat_free.cpt" || exit 1
  echo "now: python3 $HERE/check_convergence.py $out/npt_equil/npt_equil.edr"
fi
if [[ "$stage" == "extend" ]]; then
  # Continue the existing NPT rather than starting a second one: convert-tpr
  # pushes nsteps out and mdrun -cpi -append writes into the same edr/log/xtc.
  # One record means check_convergence.py blocks over the whole trajectory,
  # and the plateau artifact stays bound to that single energy file.
  d="$out/npt_equil"
  [[ -f "$d/npt_equil.cpt" ]] || { echo "no checkpoint in $d; run the npt stage first" >&2; exit 1; }
  ns="${EXTEND_NS:-10}"
  ps=$(python3 -c "print(float('$ns') * 1000.0)")
  ( cd "$d" && "$gmx" convert-tpr -s npt_equil.tpr -extend "$ps" -o npt_equil.tpr > convert_tpr.log 2>&1 ) \
        || { echo "[npt_equil extend] convert-tpr failed, see $d/convert_tpr.log" >&2; exit 1; }
  python3 - "$d" "$ns" >> "$out/stage_manifest.tsv" <<'PY'
import datetime, hashlib, sys
d, ns = sys.argv[1], sys.argv[2]
h = lambda p: hashlib.sha256(open(p, "rb").read()).hexdigest()[:16]
print("\t".join([datetime.datetime.now().isoformat(timespec="seconds"),
                 "npt_equil_extend", f"extend_ns={ns}",
                 f"tpr={h(d + '/npt_equil.tpr')}", f"cpt={h(d + '/npt_equil.cpt')}"]))
PY
  ( cd "$d" && "$gmx" mdrun -deffnm npt_equil -cpi npt_equil.cpt -append "${ntomp[@]}" >> mdrun.log 2>&1 ) \
        || { echo "[npt_equil extend] mdrun failed, see $d/mdrun.log" >&2; exit 1; }
  echo "[npt_equil] extended by $ns ns"
  echo "now: python3 $HERE/check_convergence.py $d/npt_equil.edr"
fi
if [[ "$stage" == "production" ]]; then
  # Production is gated on a PLATEAU artifact that belongs to *this* NPT
  # energy file (sha256 match). No artifact, a stale one, or NOT YET all refuse.
  edr="$out/npt_equil/npt_equil.edr"
  if ! python3 - "$edr" <<'PY'
import hashlib, json, os, sys
edr = sys.argv[1]; art = edr + ".plateau.json"
if not os.path.exists(art):
    sys.exit(f"no plateau artifact for {edr}; run check_convergence.py first")
a = json.load(open(art))
digest = hashlib.sha256(open(edr, "rb").read()).hexdigest()
if a.get("edr_sha256") != digest:
    sys.exit("plateau artifact does not belong to the current energy file (hash mismatch); re-run check_convergence.py")
if a.get("verdict") != "PLATEAU":
    sys.exit(f"convergence verdict is {a.get('verdict')!r}; production is not approved")
print(f"plateau artifact ok ({a['checked_at']}); note it does not assess: {', '.join(a.get('not_assessed_here', []))}")
PY
  then
    echo "production refused" >&2; exit 1
  fi
  run production "$HERE/production.mdp" "$out/npt_equil/npt_equil.gro" -t "$out/npt_equil/npt_equil.cpt" || exit 1
fi
