#!/usr/bin/env python3
"""Turn the PEG 200 plasticizer into a builder-ready template.

The experimental team's "PEO 1 wt%" turned out to be Sigma P3015 PEG 200
(2026-09-15 reply): a short liquid oligomer, average Mn 200, not a long
poly(ethylene oxide). That resolves what looked like a blocking problem --
a 100 kDa PEO could not be placed in a 28k-atom cell at 1 wt% -- into a
routine one: about ten small molecules.

The representative molecule is HO-(CH2CH2O)4-H (C8H18O5, 194.23 g/mol;
PEG 200 is a distribution centred near n = 4), parameterized exactly as every
other species here: LigParGen, OPLS-AA, 1.14*CM1A-LBCC, submitted as SMILES
``OCCOCCOCCOCCO`` on 2026-09-15 (``raw/PEG4.itp``/``raw/PEG4.gro`` are the
server's files verbatim).

Two things are done to it, both for the same reasons as
``build_des_components.py``:

* LigParGen mints a fresh ``opls_8xx`` namespace per submission, so the
  types are renamed with a ``pg`` prefix and appended to ``forcefield.itp``
  inside a marked fence, after the DES fence, so a re-run rewrites rather
  than duplicates.
* The moleculetype and residue become ``PEG``; a variant called ``UNK`` in
  the include path would collide with the next LigParGen molecule.

Charges are left as LigParGen wrote them here; ``apply_charges.py neutralize``
makes the sum exactly zero afterwards, as for every neutral template.

Modelling assumption, stated once: PEG 200 is treated as an unreacted, free
plasticizer. Its terminal OH groups can react with isocyanate; that is a
known caveat, not implemented, and revisited only if the dry nominal model
disagrees with experiment.
"""

from __future__ import annotations

import os

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "raw")
OUT = os.path.join(HERE, "..", "project", "structure")
FENCE_START = "; --- PEG 200 plasticizer atomtypes (build_peg_component.py) ---"
FENCE_END = "; --- end PEG 200 plasticizer atomtypes ---"
DES_FENCE_END = "; --- end DES component atomtypes ---"


def sections(path):
    """``{section: [rows]}`` with comments stripped; order of sections kept."""
    out, order, cur = {}, [], None
    for line in open(path):
        text = line.split(";", 1)[0].strip()
        if not text:
            continue
        if text.startswith("["):
            cur = text.strip("[] ").strip().lower()
            if cur not in out:
                out[cur] = []
                order.append(cur)
            else:
                # LigParGen writes two [ dihedrals ] blocks (proper, improper)
                cur_key = cur
                k = 2
                while f"{cur_key}#{k}" in out:
                    k += 1
                cur = f"{cur_key}#{k}"
                out[cur] = []
                order.append(cur)
            continue
        out[cur].append(text.split())
    return out, order


def build(residue="PEG", molecule="PEG", prefix="pg"):
    data, order = sections(os.path.join(RAW, "PEG4.itp"))
    renamed = {row[0]: f"{prefix}{row[0].split('_')[-1]}" for row in data["atomtypes"]}
    atomtype_rows = [[renamed[r[0]], f"{prefix}{r[1]}", *r[2:]] for r in data["atomtypes"]]

    lines = [
        "; Generated by build_peg_component.py from raw/PEG4.itp",
        "; (LigParGen OPLS-AA / 1.14*CM1A-LBCC, SMILES OCCOCCOCCOCCO = HO(CH2CH2O)4H).",
        f"; Types renamed with the '{prefix}' prefix; [ atomtypes ] live in forcefield.itp.",
        "[ moleculetype ]",
        f"  {molecule}     3",
        "",
        "[ atoms ]",
    ]
    for r in data["atoms"]:
        nr, atype, _resnr, _res, name, cgnr, charge, mass = r[:8]
        lines.append(f"  {int(nr):4d}  {renamed[atype]:8s}  1  {residue:5s} {name:5s} {int(cgnr):4d} "
                     f"{float(charge):10.6f} {float(mass):9.4f}")
    for sec in order:
        if sec in ("atomtypes", "moleculetype", "atoms"):
            continue
        header = sec.split("#")[0]
        lines += ["", f"[ {header} ]"]
        lines += ["  " + "  ".join(r) for r in data[sec]]
    with open(os.path.join(OUT, f"{molecule}.itp"), "w") as f:
        f.write("\n".join(lines) + "\n")

    gro_in = open(os.path.join(RAW, "PEG4.gro")).read().splitlines()
    n = int(gro_in[1])
    body = [f"{1:5d}{residue:<5s}{l[10:15]}{l[15:]}" for l in gro_in[2:2 + n]]
    with open(os.path.join(OUT, f"{molecule}.gro"), "w") as f:
        f.write("\n".join([f"{molecule} PEG 200 (n=4) plasticizer, LigParGen geometry", str(n), *body, gro_in[2 + n]]) + "\n")
    print(f"wrote {molecule}.itp ({len(data['atoms'])} atoms) and {molecule}.gro")
    return atomtype_rows


def merge_atomtypes(rows):
    path = os.path.join(OUT, "forcefield.itp")
    text = open(path).read()
    if FENCE_START in text:
        head, rest = text.split(FENCE_START, 1)
        _, tail = rest.split(FENCE_END, 1)
        text = head.rstrip("\n") + "\n" + tail.lstrip("\n")
    if DES_FENCE_END not in text:
        raise SystemExit("forcefield.itp has no DES fence to append after; run build_des_components.py first")
    block = [FENCE_START] + ["  " + "  ".join(r) for r in rows] + [FENCE_END]
    text = text.replace(DES_FENCE_END, DES_FENCE_END + "\n" + "\n".join(block), 1)
    open(path, "w").write(text)
    print(f"merged {len(rows)} PEG atomtypes into forcefield.itp")


if __name__ == "__main__":
    merge_atomtypes(build())
