paths:
  out_root: ${CONFIG_DIR}/../runs/config_2_orca_geoopt_bartender_internal

bartender_pipeline:
  relaxation: orca
  md: bartender
  workdir_name: relax_orca_geoopt
  bartender:
    output_dirname: bartender_internal
