# monomers.yaml
# Token(string) -> monomer xyz mapping.
# Keys are NOT limited to one-letter symbols.
# You can use one letter (S), words (SBMA), or any short identifier.
monomers:
  S: NEW_SBMA.xyz
  D: NEW_DMAPS.xyz
  C: NEW_CBA.xyz
  # SBMA: NEW_SBMA.xyz
  # DMAPS: NEW_DMAPS.xyz
  # CBA: NEW_CBA.xyz
